tests/test_text.py

issue #37 
I hope this test codes help you feel comfortable.

Add some tests for text.py 

---

docs/source/protocol.rst

Fix typo in example

---

README.md

Small typo in README.

---

docs/source/protocol.rst

- [*] Documentation / docstrings
- [*] I accept that @willmcgugan may be pedantic in the code review.
Close Issuse https://github.com/willmcgugan/rich/issues/61

fix error on panel module documentation.

---

rich/progress.py

Work in progress to fix https://github.com/willmcgugan/rich/issues/90

deadlock fix

---

README.md

Columns readme

---

CHANGELOG.md
pyproject.toml
rich/default_styles.py
rich/highlighter.py
rich/logging.py
rich/style.py
rich/text.py
tests/test_text.py

Fixes path + filename highlighting which didn't work well. Allowed highlight_regex to accept a callable.

Improve path highlight

---

CHANGELOG.md
examples/table.py
pyproject.toml
rich/console.py
rich/table.py

Disables legacy windows detection on Jupyter https://github.com/willmcgugan/rich/issues/125

fix for tables in Jupyter on Windows

---

rich/logging.py

Add markup support to log handler

---

CHANGELOG.md
docs/source/progress.rst
pyproject.toml
rich/bar.py
rich/progress.py
rich/segment.py

Enables progress bars with Jupyter

Jupyter progress

---

rich/prompt.py

Fix spellings Prompt.ask
Promot -> Prompt
readding-> reading

Fix spellings in Prompt.ask

---

CHANGELOG.md
docs/source/console.rst
docs/source/logging.rst
docs/source/tables.rst
examples/listdir.py
examples/rainbow.py
pyproject.toml
rich/console.py
rich/logging.py
rich/markdown.py
rich/prompt.py
rich/table.py
rich/text.py
tests/test_prompt.py
tests/test_text.py

prompt fix and text.stylize refactor

---

CHANGELOG.md
pyproject.toml
rich/box.py
rich/console.py
rich/progress.py

track optimization

---

CHANGELOG.md
pyproject.toml
rich/__main__.py
rich/console.py
rich/progress.py
tests/test_progress.py

Thread based approach to replace iter_track

Track thread

---

CHANGELOG.md
docs/source/markup.rst
docs/source/style.rst
docs/source/text.rst
pyproject.toml
rich/__main__.py
rich/color.py
rich/logging.py
rich/markup.py
tests/test_color.py
tests/test_markup.py

color parsing

---

rich/_ratio.py
tests/test_ratio.py

Thanks for this package! I found out about it today and I absolutely love it!
I made a tiny contribution to #37 (a single line) and corrected a docstring, but will try to help some more in getting coverage to 100 in the future.

Test for ratio_reduce in ._ratio

---

rich/console.py
rich/rule.py
rich/segment.py
rich/text.py

Change raw strings to strings in docstrings.

Change raw strings to strings in docstrings

---

docs/source/introduction.rst

fix demo-breaking typo

---

CHANGELOG.md
pyproject.toml
rich/highlighter.py
rich/pretty.py

faster pretty

---

README.md

The table example in the README has an unused import, remove it for cleaner example.

Remove unused import in Table example

---

CHANGELOG.md
pyproject.toml
rich/pretty.py

Fixes https://github.com/willmcgugan/rich/issues/235

fix underscore missing in repl

---

README.cn.md

Add "projects using Rich to Chinese", which was added a while ago to the English documentation to the Chinese documentation

Add "projects using Rich" to Chinese documentation

---

CHANGELOG.md
docs/source/console.rst
docs/source/index.rst
docs/source/text.rst
pyproject.toml
rich/console.py
rich/measure.py
rich/pretty.py
rich/rule.py
rich/style.py
rich/syntax.py
rich/text.py
tests/test_console.py
tests/test_constrain.py
tests/test_pretty.py
tests/test_progress.py
tests/test_protocol.py
tools/profile_pretty.py
tools/stress_test_pretty.py

Better pretty print

---

CHANGELOG.md
rich/highlighter.py

I didn't add myself to the `CONTRIBUTORS.md` as the change is very small, also I didn't add any test as the functionality I've changed doesn't have any - I don't have anything to base on. I've run only some manual tests. I
Fixes #272

Accept `#` sign in the URL.

---

CONTRIBUTORS.md
README.es.md

Translate the README.md to Spanish

Add README.es.md in Spanish/Español

---

rich/console.py
tests/test_inspect.py

Added tests and fixed documentation

---

docs/source/padding.rst

fix spelling typo

---

docs/source/logging.rst
rich/logging.py
tests/test_logging.py

Handling exceptions with rich's logging handler #298

handle exceptions with rich's logging handler

---

README.cn.md
README.es.md
README.md

As proposed in https://github.com/willmcgugan/rich/issues/309

Add reference to rich usage case 'norfair' in README

---

CHANGELOG.md
rich/progress.py
tests/test_progress.py

Incorporates #323 
I have just changed the prefixes to binary as suggested in the issue
Edit: Checked off a few more boxes and added the description at the correct place

Change to binary prefixes in progress.py

---

README.cn.md

Remove the part which has been removed in the English version (b8cd13e4eb5f8508192c08eb93157026b708d575)

Remove the part has been removed from English version

---

CHANGELOG.md
rich/console.py
rich/pretty.py
rich/style.py
rich/syntax.py
rich/traceback.py

Just some semi-automatically found typos.

Fix typos, comments, unused imports

---

tests/test_live_render.py

Basic test for object LiveRender
I saw there are no direct test for the object LiveRender.

Add test_live_render

---

examples/exception.py

Added a simple example with an exception traceback

Demo exception

---

tox.ini

Add tox configurations

---

CHANGELOG.md
docs/source/console.rst
examples/top_lite_simulator.py
rich/align.py
rich/console.py
rich/default_styles.py
rich/live.py
rich/rule.py
tests/test_rule.py

Adds align paramter to Rule

---

README.cn.md
README.es.md
README.md

added `import sys` statement to the columns example in README.md

add import to columns example in README.md

---

rich/live.py

Removes the double ipython output display found in #485. 
I'm not quite sure why, but the final refresh for a live must occur after popping the render hooks.

fix issue causing jupyter console to double print

---

docs/source/syntax.rst

[Docs] File needs to be in read mode

---

CHANGELOG.md
pyproject.toml

new version

---

docs/source/progress.rst

Fixed small issue with example code for docs on progress usage with logs.

Add description field and f-string to progress logs example

---

CHANGELOG.md
rich/__init__.py
rich/_inspect.py
rich/logging.py
rich/pretty.py
tests/test_inspect.py

Refactor logging

---

CHANGELOG.md
docs/source/progress.rst
rich/pretty.py
rich/traceback.py
tests/test_pretty.py

tweaks to ipython, add margin

---

rich/_inspect.py
rich/default_styles.py
rich/logging.py
tests/test_inspect.py

draw panel around value in inspect

---

CHANGELOG.md
pyproject.toml
rich/default_styles.py
rich/traceback.py

fix encoding

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
rich/align.py
rich/panel.py
rich/progress_bar.py
tests/test_align.py
tests/test_bar.py

no color progress fixes

---

CHANGELOG.md
rich/console.py
rich/syntax.py

bump version

---

docs/source/introduction.rst
docs/source/prompt.rst

Corrects a grammatical mistake in the documentation.

fix grammatical mistake in docs

---

CHANGELOG.md
pyproject.toml
rich/_inspect.py
tests/test_inspect.py

Fixed https://github.com/willmcgugan/rich/issues/916

fix TypeError in inspect

---

CHANGELOG.md
pyproject.toml
rich/live.py

fix deadlock

---

.coveragerc
CHANGELOG.md
docs/source/console.rst
pyproject.toml
rich/_timer.py
rich/console.py
rich/containers.py
rich/default_styles.py
rich/rule.py
rich/scope.py
rich/segment.py
rich/status.py
rich/style.py
rich/syntax.py
rich/table.py
rich/text.py
rich/traceback.py

Optimizations

---

docs/source/logging.rst

Fixed a typo
Thanks for your super work!

Corrected typo in Logging Handler docs.

---

README.sv.md

I added my own written swedish translation, made with google translate, own knowledge, deep dive into swedish programming forums, and annoying other swedish devs on Discord with translation questions

Added a swedish translation of the README

---

README.ja.md
README.md

I added Japanese translation of README.
I think Rich is a very cool project, and I would be happy to using it to more Japanese developers by adding a Japanese README :)

Added a Japanese translation of the README

---

README.cn.md

docs: update some style

---

README.es.md

Update README.es.md adding collapsable sections and other seccions to Spanish

Update README.es.md collapsable sections

---

README.md

missing text

---

CHANGELOG.md
rich/align.py
rich/panel.py

align should reset height

---

CHANGELOG.md
pyproject.toml
rich/console.py

optimized options

---

CHANGELOG.md
pyproject.toml
rich/padding.py

Padding optimization

---

examples/downloader.py

- [x ] Documentation / docstrings
- [x ] I've run the latest [black](https://github.com/psf/black) with default args on new code.

Updated ubuntu release url

---

README.sv.md

Updated the swedish readme to match current version of english readme.

Updated readme.sv.md

---

CHANGELOG.md
rich/logging.py
rich/pretty.py

no double tracebacks

---

README.de.md

I translated the README.md into German with a clear conscience.
This is my first ever PR, so please bear with me.

Added german readme

---

CHANGELOG.md
pyproject.toml
rich/console.py
rich/jupyter.py
rich/layout.py
rich/pretty.py

Jupyter echosystem

---

README.sv.md

Updated swedish readme to include the bragging rights badge hehe

bragging rights but swedish

---

.github/workflows/readmechanged.yml

Let authors of translations will be notified in this [discussion](https://github.com/willmcgugan/rich/discussions/1174) when **README.md** changed .

Add Workflow when README.md changed

---

examples/top_lite_simulator.py
poetry.lock
rich/_ratio.py
rich/align.py
rich/box.py
rich/console.py
rich/live_render.py

fix warnings due to import errors

---

rich/__init__.py

Fixed typo

---

.github/workflows/readmechanged.yml
README.es.md

* Update the README.es.md 
* Update readmechanged.yml workflow to run on master upstream

Update README.es.md and readmechanged.yml  

---

CHANGELOG.md
examples/attrs.py
poetry.lock
pyproject.toml
rich/pretty.py
tests/test_pretty.py

Adds pretty printing support for attrs module.

Pretty attrs

---

README.es.md

Add link to Korean translation README

Add link to Korean translation readme

---

CHANGELOG.md
pyproject.toml
rich/markdown.py

fix for markdown in layout

---

rich/layout.py

~~- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.~~
~~- [ ] I've added tests for new code.~~
The module `Panel` was unused. It can be removed.

style: remove unused import

---

rich/logging.py

Fix docstring typo

---

CHANGELOG.md
docs/source/markup.rst
poetry.lock
rich/_emoji_replace.py
rich/align.py
rich/cells.py
rich/console.py
rich/emoji.py
rich/markup.py
rich/segment.py
rich/tabulate.py
rich/text.py
rich/traceback.py
tests/test_box.py
tests/test_console.py
tests/test_emoji.py
tests/test_live_render.py
tests/test_padding.py
tests/test_segment.py

Height fixes

---

rich/markdown.py

Quick fix for #1350
No real code added, just a fix in the docs as pointed out in #1350

Fix Markdown() documentation

---

.github/workflows/codespell.yml
CONTRIBUTORS.md
README.fr.md
README.md

Translation of the README into French

Translation of the README into French

---

README.md

A tiny grammar mistake was fixed: changed generate to generates.

Fixed a small grammar mistake

---

.github/workflows/codespell.yml
README.de-ch.md
README.md

A Swiss German version. I guess every Swiss would write it a little different in his own way.

Create Swiss German README

---

docs/source/pretty.rst

- [ x] Documentation / docstrings
This should be self explanatory ;)

Fix a typo in the docs

---

.github/workflows/comment.yml

I think there was a missing word here. 🤔

Adjust issue-close comment wording.

---

CHANGELOG.md
pyproject.toml
rich/__init__.py
rich/console.py
rich/default_styles.py
rich/highlighter.py
rich/json.py
tests/test_console.py
tests/test_rich_print.py

Json color

---

.github/workflows/pythonpackage.yml
rich/__main__.py
rich/_emoji_replace.py
rich/color.py
rich/columns.py
rich/console.py
rich/containers.py
rich/progress.py
rich/protocol.py
rich/screen.py

Removes unused imports. These imports were unused by mypy as well.

Remove unused imports

---

.github/ISSUE_TEMPLATE/feature_request.md

This is just a minor typo I noticed in the issue template

Minor typo in template

---

rich/console.py
tests/test_console.py

Closes https://github.com/willmcgugan/rich/issues/1640

fix detect color

---

CHANGELOG.md
rich/live.py
tests/test_live.py

fix for missing newline

---

rich/console.py

legacy windows fix

---

docs/source/conf.py
docs/source/console.rst
docs/source/prompt.rst
rich/console.py

This attempts to resolve #1633.

Mention the usage of Python's builtin readline module in the documentation

---

CHANGELOG.md
rich/markdown.py
tests/test_log.py

Fixes https://github.com/willmcgugan/rich/issues/1515

word wrap code blocks

---

CHANGELOG.md
rich/pretty.py
tests/test_pretty.py

Closes https://github.com/willmcgugan/rich/issues/1599

fix trailing comma

---

CHANGELOG.md
rich/live.py
rich/progress.py
tests/test_live.py

Fixes https://github.com/willmcgugan/rich/issues/1662

new lines fixes

---

rich/text.py

Fix the text.Span.__repr__ method

---

README.pt-br.md

Fix small typo on the Portuguese README

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
rich/console.py
rich/live.py
rich/live_render.py

revert thread safety issue

---

examples/downloader.py

Related to #1749
The URL specified in the doc string as an example to try no longer exists and returns a 404. I updated it to the current working URL.

Update example url

---

CHANGELOG.md
pyproject.toml
rich/text.py
tests/test_segment.py

Fix issue with overlapping markup.

fix for overlapping markup

---

CHANGELOG.md
pyproject.toml
rich/markup.py
tests/test_markup.py

Fix @ symbol not being escaped

fix at escape

---

README.cn.md
README.de-ch.md
README.de.md
README.es.md
README.fr.md
README.hi.md
README.it.md
README.ja.md
README.kr.md
README.md
README.pt-br.md
README.ru.md
README.sv.md

Added Russian translation of README.md and a link to it

Added Russian README

---

CHANGELOG.md
rich/pretty.py
tests/test_pretty.py

Adds a max_depth arg to pretty printing.

max depth arg

---

.github/ISSUE_TEMPLATE/bug_report.md

This change tries to reduce noise in bug reports.
Example: https://github.com/Textualize/rich/issues/1838

Collapse platform details in bug reports

---

CHANGELOG.md
rich/_inspect.py
rich/pretty.py
tests/test_inspect.py

The "Swig global variables object" has an empty `dir()` (🤷‍♂️) so that attribute access of `.__class__` fails. I'm not sure what else we can do other than patch this particular case by checking for the `__class__` attribute.
Fixes #1838

Define and use a safe `isinstance` which handles exceptions

---

rich/markdown.py

Typo: THe -> The

---

docs/source/style.rst

Fixes a typo in the `Styles` documentation.

docs(style): fix typo

---

CHANGELOG.md
rich/tree.py
tests/test_layout.py
tests/test_tree.py

Fixes https://github.com/Textualize/rich/issues/1608

disable pad if justify is None

---

rich/console.py

Fixes broken prompt on Windows.
Removes a workaround for colorama.

simplify prompt

---

.pre-commit-config.yaml
examples/downloader.py
rich/__init__.py
rich/_win32_console.py
rich/_windows.py
rich/control.py
rich/highlighter.py
rich/pager.py
rich/protocol.py
rich/traceback.py
tests/test_ansi.py
tests/test_live.py
tests/test_lrucache.py
tests/test_panel.py
tests/test_table.py
tools/make_emoji.py

I saw `pycln` (which is a formatter for finding and removing unused import statements) a good addition to the current pre-commit hooks which I believe would ensure a high code quality standard besides `black` and `isort`. 
BTW, I'm the author of `pycln` 😄.
Anyway, please feel free to ask any questions and/or reject/close this PR.
\+ I would like to thank you for inventing this incredible library!

Pycln QA tool as a pre-commit hook

---

.github/workflows/update_benchmark_website.yml

Benchmarks can be run on any machine. Result data included in rich repo. When a release is made, new HTML will be published.

GitHub Action to publish ASV HTML and copy to `rich-benchmarks`

---

poetry.lock
pyproject.toml
rich/ansi.py
rich/segment.py

Reverts an optimization in the Segment class which unfortunately broke typing when unpacking.

revert segment optimization

---

CONTRIBUTORS.md
rich/__init__.py

Return IPython extension

---

rich/ansi.py
tests/test_ansi.py
tests/test_text.py

fix for ansi issue

---

poetry.lock
pyproject.toml

Fixes dependancy issue https://github.com/Textualize/rich/issues/2150

bump typing extension

---

.github/workflows/codespell.yml
CHANGELOG.md
CONTRIBUTORS.md
README.id.md

I'm adding Indonesian translation for the readme section

adding indonesian translation for readme

---

CHANGELOG.md
rich/markup.py
tests/test_markup.py

Fixes Markup escaping issue https://github.com/Textualize/rich/issues/2187

fix escaping issue

---

.github/workflows/codespell.yml

Do not codespell any foreign language README.*.md

---

rich/pretty.py

Missing `f` prefix on f-strings fix

---

examples/downloader.py

Fix typo in examples/downloader.py

---

CONTRIBUTORS.md
docs/source/console.rst

- I updated CONTRIBUTORS.md, not sure this is worth adding to the CHANGELOG, what do you think?
Fix a micro typo in the docs for the Console API.

✏ Fix micro typo "in to" to "into"

---

README.pt-br.md

Original english text was not removed.
Original english text was not removed after translated.

Fix typo in the README.pt-br.md

---

README.ru.md

 RU spelling errors

---

CHANGELOG.md
CONTRIBUTORS.md
README.cn.md
README.de-ch.md
README.de.md
README.es.md
README.fa.md
README.fr.md
README.hi.md
README.id.md
README.it.md
README.ja.md
README.kr.md
README.md
README.pt-br.md
README.ru.md
README.sv.md
README.tr.md
README.zh-tw.md

Add new README.md files for Turkish developers. [Readme.tr.md](README.tr.md)

Add Turkish Language

---

docs/source/conf.py

docs: update copyright year

---

CHANGELOG.md
rich/console.py
tests/test_console.py

Adds an exception for Kitty terminal.

Add Kitty exception

---

docs/source/introduction.rst

Docs review of Introduction

---

docs/source/console.rst

Docs review of Console

---

docs/source/progress.rst

Add the missing quote mark to progress.rst.

add a missing quote to progress.rst

---

CHANGELOG.md
rich/file_proxy.py

Fixes https://github.com/Textualize/rich/issues/2668

fix for fileno

---

rich/color.py
rich/console.py
rich/file_proxy.py
rich/json.py
rich/markdown.py
rich/progress.py
rich/repr.py
rich/segment.py
rich/syntax.py
rich/text.py
rich/traceback.py

Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>
After the mention on PythonBytes, I thought I'd try running refurb on rich - and I actually had already tried this earlier! These were the changes that looked pretty reasonable; I didn't make the ones that didn't seem better to me, and I also skipped the "else" ones, which I do think are better but can be a bit polarizing.

chore: apply some refurb suggestions

---

poetry.lock
pyproject.toml

Bump pygments to ^2.14.0 and relaxed ipywidgets dep

---

CHANGELOG.md
pyproject.toml
rich/color.py

Fix the color reduction algorithm for 16.7 million colors to xterm 256 colors

fix for color downgrade

---

CHANGELOG.md
CONTRIBUTORS.md
README.cn.md
README.de-ch.md
README.de.md
README.es.md
README.fa.md
README.fr.md
README.hi.md
README.id.md
README.it.md
README.ja.md
README.kr.md
README.md
README.pl.md
README.pt-br.md
README.ru.md
README.sv.md
README.tr.md
README.zh-tw.md

Translated README.md to Polish in original's format.

add: README.pl.md in Polish

---

rich/align.py

fix: typo in align.py

---

.github/workflows/pythonpackage.yml

* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-python/releases
* https://github.com/snok/install-poetry/releases
* https://github.com/codecov/codecov-action/releases

Upgrade GitHub Actions

---

CHANGELOG.md
rich/_export_format.py
tests/test_console.py

Fixes https://github.com/Textualize/rich/issues/2832

fix pre output

---

.github/dependabot.yml

Add github-actions to `dependabot.yml`

Add github-actions to `dependabot.yml`

---

CHANGELOG.md
rich/syntax.py
rich/text.py
rich/traceback.py

Fixes https://github.com/Textualize/rich/issues/2821

Empty traceback frames

---

CHANGELOG.md
rich/live.py

Fixes https://github.com/Textualize/rich/issues/2726

fix markup in console live

---

CHANGELOG.md

version bump

---

CHANGELOG.md
pyproject.toml
rich/style.py
rich/text.py
tests/test_style.py

Adds a Style.clear_meta_and_links method

Added Style.reset method

---

CHANGELOG.md
pyproject.toml
rich/syntax.py

Fix italic guidelines in SVG screenshots

fix superfluous italics

---

CHANGELOG.md
rich/markup.py
tests/test_markup.py

Fixes https://github.com/Textualize/rich/issues/2987

Fix escaping trailing backslash

---

docs/source/markup.rst

Fix a minor problem in the document.
There is an extra closing bracket in the document

Fix markup.rst

---

CHANGELOG.md

Fix nonsensical date in changelog

---

CONTRIBUTORS.md
README.es.md

✏️ Fix micro-typo in README.es.md

✏️ Fix micro-typo in README.es.md

---

README.tr.md

I corrected the incorrect usages in the README.tr.md file as a native Turkish speaker.

✏ Fix Typo Errors in README.tr.md As A Native Turkish Speaker ✏

---

docs/source/progress.rst
docs/source/tables.rst
docs/source/text.rst
rich/pretty.py

Just some minor mistakes I found while reading the (otherwise excellent!) docs.

[docs] Fix typos and other small stuff

---

docs/source/reference/text.rst
rich/text.py

Export TextType into the docs.

---

docs/requirements.txt
docs/source/conf.py
pyproject.toml
tests/test_syntax.py

Fix warning in test suite

---

.github/workflows/pythonpackage.yml

I think it might fix the latest macOS error

Fix CI for macOS ARM

---

poetry.lock
pyproject.toml
tests/test_console.py

- Add some tests
- Update lockfile

console test

---

CONTRIBUTORS.md
docs/source/progress.rst
examples/downloader.py
rich/live.py
rich/progress.py

Hi, just some tiny fixes I noticed while reading the doc. Thanks for maintaining rich, it's great :)

Fix some typos and update one example

---

rich/panel.py

- [NA] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate. (I don't feel like this update is worthy of either a CHANGELOG or CONTRIBUTORS entry.
- [NA] I've added tests for new code.
Fix #3609.

Update docstring to reflect that box is not optional

---

CHANGELOG.md
pyproject.toml

bump to 14.0.0

---

README.pl.md

Fix typos in Polish README

---

rich/console.py

Reduce the number of times size is called.

optimize size
