Textualize/rich

README.md

I cant change the screenshot, so hopefully that can be updated by you.

Too many zeros

---

rich/console.py

docs(console.py): Change 'inline_styes' to 'inline_styles' in 'export_html()' doc.

---

tests/test_box.py
tests/test_console.py

I have added `test_box.py` with additional box.py tests and I have added a basic test for console.input() in `test_console.py` for issue #37.
Unfortunately, the total coverage didn't change from 94% but hope it helps in the long run. Let me know if I should change anything. Thanks!

Add input and box tests

---

CHANGELOG.md
rich/markdown.py

Allow for DRY:er subclasses by allowing us to reuse `Heading.create`
- There's no CONTRIBUTORS.md file to update, I did update the CHANGELOG.md
- This is a tiny change mainly changing one function to adhere to the other functions. Since you are currently not testing subclassing for the other classes I didn't add anyone here.
The `markdown.Headings` class unlike all other `MarkdownElement` subclasses were using an explicit self reference in it's factory/create-method. This forced us to overload the create-method every time subclassing Heading so that we could reference the new subclass instead (or as I used, a self reference). By using the implicit `cls`-reference instead we don't need to …

Allow for easier subclassing

---

docs/source/syntax.rst

This is a tiny fix to the code in the docs so the syntax example code works - hopefully you're fine I didn't run black, update CHANGELOG.md etc (given how small change is)
BTW: this library is awesome :sunglasses:  - thank you for creating it!

Lower case "console" in import makes example fail

---

CHANGELOG.md
examples/link.py
pyproject.toml
rich/console.py
rich/style.py
tests/render.py

Adds a link id to the Style class. Link ids are used when generating the ansi codes for links, so that the terminal knows which cells to highlight.
Formerly if a link contained multiple styles, the terminal would highlight individually styled portions of text on hover rather than the entire link. 
For example, printing this would look like the words ``Hello`` and ``World`` were two links, when they are actually one link.
"[link=https://example.org]Hello [b]World![/b][/link]"
This PR fixes that.

new link ids

---

rich/syntax.py

The syntax command line tool, displays markdown as the type of render.
Also, black was changing files I didn't modify, so I didn't commit that.

Syntax module: correct description

---

rich/text.py

Fix docstr in text.py (Trip to Strip) in rstrip()

Fix docstr in text.py (Trip to Strip) in rstrip

---

docs/source/logging.rst

Running the example code for logging at https://rich.readthedocs.io/en/latest/logging.html with the `extras={"markup": True}` example, I get the following error:
```python
Traceback (most recent call last):
File "minimal_example/test.py", line 9, in <module>
log.error("[bold red blink]Server is shutting down![/]", extras={"markup": True})
File "/Users/philewels/miniconda2/envs/python3/lib/python3.6/logging/__init__.py", line 1335, in error
self._log(ERROR, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'extras'
```
Looking over the [Python `logging` docs](https://docs.python.org/3.8/library/logging.html#logging.Logger.debug), it seems that the logging argument is `extra` without the `s`:
> There are four keyword arguments in _kwargs_ which are inspected: …

Logging docs - fix 'extras' typo

---

rich/console.py
rich/logging.py

I saw a reference to this issue in #72. 
Update the Console and RichHandler class to include show_time and show_level.

Update RichHandler to include all flags of LogRender

---

.github/workflows/pythonpackage.yml
Makefile
rich/_palettes.py

Added a check for black formatting to ensure only formatted code is merged to the master branch.

Add black format check to ci

---

README.cn.md

In the original Chinese README.md, the badges aren't the same with the recently updated English one. This pull request updates the badges in Chinese README.md to be the same with the English one.

Update badges for chinese README.md(sync with english README.md)

---

rich/markup.py
tests/test_markup.py

Fix deprecation warnings due to invalid escape sequences.

---

rich/traceback.py
tests/test_traceback.py

Another small contribution to #37 . I am not so sure about the last two tests, because I couldn't exactly pinpoint what the traceback is supposed to do in those cases. 
Also: I added a `no cover` statement. I noticed that when I add a print statement before the `break`, both the `break` and the print are reached according to coverage (which makes sense). When I remove the print, the `break` isn't reached anymore. Not sure what happens there, might be a bug in ~~pytest~~ _coveragepy_?
Happy to make some changes / additions to this PR. Let me know if you need or want it. Thanks!
**Edit:** formatting and small change in wording

Tests on traceback to 100% coverage

---

rich/_ratio.py

There is a small typo in rich/_ratio.py.
Should read `guaranteed` rather than `garanteed`.

docs: Fix simple typo, garanteed -> guaranteed

---

rich/console.py

fix spelling of 'anything' in console.py docstring

fix spelling of 'anything' in console.py docstring

---

CHANGELOG.md
examples/group2.py
examples/padding.py
rich/console.py
rich/markdown.py
rich/syntax.py
rich/text.py
tests/test_markdown.py

Syntax highlights inline code in Markdown

inline code in Markdown

---

rich/progress.py

When working with `rich` download progress bars with `httpx` we were finding the transfer speed jumping around all over the place.
For example, this snippet...
```python
import tempfile
import httpx
import rich.progress
with tempfile.NamedTemporaryFile() as download_file:
url = "https://speed.hetzner.de/100MB.bin"
with httpx.stream("GET", url) as response:
total = int(response.headers["Content-Length"])
with rich.progress.Progress(
"[progress.percentage]{task.percentage:>3.0f}%",
rich.progress.BarColumn(bar_width=None),
rich.progress.DownloadColumn(),
rich.progress.TransferSpeedColumn(),
) as progress:
download_task = progress.add_task("Download", total=total)
for chunk in response.iter_bytes():
download_file.write(chunk)
progress.update(download_task, …
```

Bump up the total number of `ProgressSample` items.

---

pyproject.toml

This updates `pyproject.toml` to use `poetry-core` to build instead of the full `poetry` so that `rich` and projects that depend on `rich` will successfully build with `pip install --no-binary :all: rich`: https://github.com/python-poetry/poetry/issues/1975#issuecomment-684773959 . There are currently a couple formulae in macOS Homebrew that are blocked due to this, eg https://github.com/Homebrew/homebrew-core/pull/59954

use poetry-core to build

---

CHANGELOG.md
rich/console.py
tests/test_console.py

Missing to specify encoding can mess some clients which may break the file encoding or render it incorrectly.
Example: file that loads ok locally, after upload to S3 gets broken if the encoding is not mentioned in file.
Use of UTF-8 is a very good practice, but we still need to mention it.
```
aws s3 cp report.html s3://bucket/report.html
```
The table drawing characters are those that are getting broken when not using UTF-8 but I can suspect that the same could happen with other Unicode characters too. [example](https://sbarnea.com/gri/ssbarnea.html) renders ok in Chrome but bad in Firefox, but once the charset is mentioned the issue is sorted.
Note: I don't think I deserve a mention in CONTRIBUTORS.md ;)

Fix broken HTML encoding

---

rich/console.py
rich/syntax.py

Fix typo and remove a missing argument in the docstring

Fix typo and remove a missing argument in the docstring

---

tests/test_pretty.py

Fixes #255.
Ensures sets in `tests/test_pretty.py::test_pretty` only contain one element. The ordering of sets is non-deterministic and can change between platforms. Having multiple items in the set causes the test to fail on some platforms.

Don't rely on set ordering for test data

---

rich/containers.py
rich/table.py
tests/test_containers.py
tests/test_measure.py
tests/test_padding.py
tests/test_table.py

Some additional tests in response to #37 for the following files:
* `measure.py`
* `test_null_get`: Checks for cases where `Measurement.get()` should return `Measurement(0, 0)`
* `test_measure_renderables`: Tests that `measure_renderables` returns the correct `Measurement` object 
* `table.py`
* `test_append_column`: Checks whether headers are correctly added to `self.columns` in `Table`. I'm not too sure if this test is meaningful enough though.
* `test_rich_measure`: Checks whether the `__rich_measure__` method of `Table` returns the correct `Measurement` object for several cases
* Tried to add a test for lines 496-497, however I can't engineer a case where the code in `try` would raise a `ValueError`:
```python
try:
second_max_column = max(
width if allow_wrap and width != max_column …
```

Additional tests for `measure.py`, `table.py`, `padding.py` and `containers.py`, as well as some possible code fixes

---

README.md

Documents use of rich by molecule and ansible-lint, two popular command line tools with over 2k github stars.
I am totally ok if you refuse this PR as sooner or later you will have to stop pubishing list of users on the README. I seen this becoming a real issue with cookiecutter project. Still, I do think that listing few high-profile projects could help advertise rich to others.

Document use of rich by molecule and ansible-lint projects

---

README.md

Signed-off-by: Zethson <lukas.heumos@posteo.net>
We are delighted to see that you like [nf-core](https://nf-co.re/), but the URL wasn't quite right :)
Cheers!

fixed nf-core URL in README

---

docs/source/console.rst

According to the code (and reference), the argument is "styles=True" rather than "style=True".

doc: Fix styles=True typo for pager

---

rich/__main__.py

- I have changed the Korean text to a more appropriate translation, assume that the original English text was "The library supports Chinese, Japanese, and Korean texts".
- I have not run the formatter or updated CHANGELOG, since it is a really minor change.
- I think that [imgs/features.png](https://github.com/willmcgugan/rich/blob/master/imgs/features.png) should reflect the change, but I do not know how to do it. Could you help me with this?

Fix translation of Korean texts.

---

rich/jupyter.py
rich/pretty.py
rich/prompt.py

Hi, 
The error occurs when using pyoxidizer to packaging python application depends on rich. It seems below import can't be handled in pyoxidizer:
```
from .__init__ import something
```
The related pyoxidizer issue: https://github.com/indygreg/PyOxidizer/issues/317

resolve pyoxidizer compatible issue

---

rich/logging.py

- [x ] I accept that @willmcgugan may be pedantic in the code review.
The standard logging module accepts either str or int as a logging level. str is internally casted to int. Rich does not do anything with the logging level so there is no reason to limit the type here.

Changes typing for logging level to accept both str and int

---

rich/traceback.py

#493 I fix this. Just one change.
Looking in the blame, seems this was previously called code_width and was set to 88. This updates the Traceback Class to match the same parameters as the install() function.

Revert traceback console width to 100.

---

docs/source/live.rst
docs/source/tables.rst

fix typo in docs

---

examples/downloader.py

The *Try with* URL in `examples/downloader.py` hits a *404 Not Found* page. It appears on the https://releases.ubuntu.com/20.04/ page, that Ubuntu version `20.04` is no longer offered as a download. Instead version `20.04.1` is offered. I updated the URL in the script to the new version.

Update Ubuntu URL in downloader example

---

CONTRIBUTING.md

Just like other Module names make should also be in tick marks like this `make`.
It can be a little confusing for newbies.
Just like the other module names make also should be inside tick marks like this `make`

make in the line 33 should be `make` .

---

docs/source/progress.rst

The example for [Progress Display Advanced Usage](https://rich.readthedocs.io/en/stable/progress.html#advanced-usage) throws an error
``` 
Traceback (most recent call last):
File "main.py", line 13, in <module>
time.sleep(0.02)
NameError: name 'time' is not defined
```
```import time``` needs to be added.
Fixed the Progress Display Advanced Usage example

Fixed the Progress Display Advanced Usage example

---

rich/traceback.py

Nothing too special, just changes `Traceback.from_exception()` to not rely on the specific class name and rather refer to `cls`. I'm guessing this probably wasn't meant to be subclassed, but it doesn't hurt to change this.
Haven't added any tests, but I could add a test looking somewhat like this if you think it makes sense to do so:
```py
class SubclassTraceback(Traceback):
pass
try:
1 / 0
except Exception:
assert isinstance(SubclassTraceback.from_exception(*sys.exc_info())
```

Use `cls` instead of class name in `Traceback.from_exception()`

---

rich/__init__.py

Fix spelling mistake for the word "beginning".

fix spelling in docstring

---

CHANGELOG.md
CONTRIBUTORS.md
rich/markdown.py
rich/syntax.py

If user provides no PATH or uses "-" as PATH, markdown is read from sys.stdin.
Examples:
```bash
python -m rich.markdown < README.md
cat README.md | python -m rich.markdown
```

allow stdin on rich.markdown / rich.syntax

---

rich/prompt.py

The "Args:" section of the docstring was slightly off when compared to other docstrings. Corrected the indentation to make
it consistent with other docstrings.

fix text indentation in docstring

---

rich/live.py

Rich instead of importing from the top-level package using the module name alone, uses module name with `__init__` which makes it get imported twice (under names: `rich` and `rich.__init__`).
Minimal reproduction:
```py
import sys
import rich.live
print(sys.modules["rich"])
print(sys.modules["rich.__init__"])
```
I found out about it because [mypy is complaining about it](https://github.com/python/mypy/issues/8944) just because I use rich in my project. However, even if you skip that, this could still possibly lead to some strange issues when depending on the fact that modules in Python are singletons.

Stop `rich.live` from importing same module under a different name

---

rich/syntax.py

Fixes #910 
Let me know if there's a need for adding a test case for this.

Use `>` as line pointer when `legacy_windows` option is enabled

---

docs/source/console.rst

Corrects the documentation errors of the `Console API` section in the Rich documentation.

Correct 'Console API' documentation errors

---

docs/source/style.rst

A minor doc fix that corrects a typo where 'in' was used in the place of 'an'.

Correct typo in Styles section of docs

---

rich/console.py

Corrected a few things in the docstring of the method `_collect_renderables` in `rich.console.Console` class. Major changes:
1. the arguments `sep` and `end` were documented as `optional` while they are not optional -- corrected.
2. corrected the grammatical mistakes and typos.

fix incorrect texts in docstring

---

rich/logging.py

The documented default for `tracebacks_word_wrap` is not the actual default.

Fix the documented default of `tracebacks_word_wrap`

---

docs/source/layout.rst

Added a missing closing quote to an example in the `Layout` docs.
---
Thanks for the project, looking forward to trying out the new `Layout`!

Add missing closing string quote to Layout example in doc

---

docs/source/live.rst

👆 Love this
Stumbled into a missing leading f in an `f-string` in one of the docs examples.  Feel free to accept the PR or close and make the fix yourself.

fix f-string with missing f

---

rich/_log_render.py
rich/logging.py

I really like the RichHandler for logging, but I find it not so nice that it omits time values if the line above has the same time value. The Main reason is, that I often send snippets of log messages around and then the time is missing because everything happened within a second. My change is a `repeat_same_time=True` switch to RichHandler (and LogRender) to turn off this behavior. 
``` python3
import logging
from rich.logging import RichHandler
logger = logging.getLogger()
logger.addHandler(RichHandler(repeat_same_time=True))
logger.error("A")
logger.error("B")
```
Before (or with `repeat_same_time=False`):
```
[03/13/21 13:35:55] ERROR    A
ERROR    B
```
After:
```
[03/13/21 13:36:08] ERROR    A
[03/13/21 13:36:08] ERROR    B

add option to not omit identical time values in log renderer

---

README.sv.md

Updated README.sv.md to match README.md

---

examples/layout.py
rich/layout.py

Resolves a TypeError when running `examples/layout.py` using `rich=10.0.0`.
Whilst upgrading from `9.13.0` to `10.0.0` within my application I encountered a breaking changed related to `direction` being removed and replaced with the new [Splitter](https://rich.readthedocs.io/en/latest/layout.html?highlight=split_column#creating-layouts) class as outlined in the [changelog](https://github.com/willmcgugan/rich/releases). 
Upon inspecting the source and running the example I noticed it had not been updated to reflect the latest changes.
This PR removes the unused `Direction` literal and updates `example/layout.py` to use `split_row` instead of `direction="horizontal"` to help others quickly identify the necessary change.  
Run `examples/layout.py` using `rich==10.0.0` to produce the …

Updates example/layout.py to use Splitter class

---

rich/traceback.py
tests/test_traceback.py

This updates the shown traceback so that it does not include a colon if there is no exception message. This is in line with Python's default traceback handler.
Here's a screenshot that will probably explain it even better:

Stop showing colon after exception type when there is no message

---

examples/top_lite_simulator.py
pyproject.toml
rich/_ratio.py
rich/align.py
rich/box.py
rich/console.py
rich/live_render.py
tox.ini

Use `typing-extensions` package only in Python < 3.8. Python 3.8+ has everything in the built-in `typing` module.
Note: I didn't update `poetry.lock` as this causes a major change to everything. I don't really know how poetry-based workflow works.

Use typing-extensions on py<3.8 

---

CHANGELOG.md
examples/table_movie.py
rich/align.py
rich/console.py
rich/panel.py

Adds a Console.measure convenience methods.
This is convenient because you don't need an extra import. It can also be shorter if you are using default options.

add Console.measure

---

docs/source/layout.rst

~~- [ ] I've run the latest [black](https://github.com/psf/black) with default args on new code.~~
~~- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.~~
~~- [ ] I've added tests for new code.~~
This is a small documentation fix. The code bloc at https://github.com/willmcgugan/rich/blob/master/docs/source/layout.rst is not recognized as one.
This also removed some trailing spaces.

Fix layout doc codebloc

---

CHANGELOG.md
CONTRIBUTORS.md
rich/console.py
tests/test_log.py

This change improves the performance of the `Console.log` method by avoiding an expensive call to `stack()` and using `currentframe` instead. The same information is then available by navigating backward as many levels as required and peeking at the `code` object.

perf(console): avoid call to inspect.stack when possible

---

docs/source/pretty.rst

Fix small typo in Rich Repr documentation

---

.github/workflows/codespell.yml
docs/source/console.rst
docs/source/progress.rst
rich/color_triplet.py
rich/pretty.py
rich/progress.py
rich/syntax.py
rich/traceback.py
tests/test_progress.py
tools/cats.json

Create a GitHub Action (runtime ~8 sec.) to use [codespell](https://github.com/codespell-project/codespell) to discover typos.
Output: https://github.com/cclauss/rich/actions

Fix typos discovered by codespell

---

CHANGELOG.md
CONTRIBUTORS.md
rich/filesize.py
tests/test_filesize.py

Simply adds a couple of optional paramters to the `filesize.decimal()` function that allows the user to set their precision (number of decimal places) and the separator between the value and the units. In my project, I have a utility with this functionality, but I also depend on Rich. It would be great to remove that utility without having to change the filesize formats.
All changes are backward-compatible.

Decimal formatting

---

CHANGELOG.md
rich/markup.py
tests/test_markup.py

Fixes https://github.com/willmcgugan/rich/issues/1334

fix for markup span sorting

---

rich/table.py

Adds missing `overflow` arg to `add_column` docstring.

Add missing overflow arg in add_column docstring

---

rich/emoji.py
rich/jupyter.py

Refs https://github.com/python/mypy/pull/10864
This prop was missing from `__slots__` 🙂 
There's one more thing: current `__slots__` setup does not work:
```python
>>> e = Emoji('2nd_place_medal', variant='text')
>>> e.__slots__
['name', 'style', '_char']
>>> e.__dict__
{'variant': 'text', 'a': 1, 'bb': 1}
>>> e.a = 1  # should fail, but does not
>>> e.bb = 1  # should fail, but does not
```
This happens due to the fact that `JupiterMixin` does not have `__slots__ = ()` defined.
I can add it if you wish 🙂

Adds missing prop to `__slots__` of `Emoji`

---

README.cn.md
README.de-ch.md
README.de.md
README.es.md
README.fr.md
README.ja.md
README.kr.md
README.sv.md

Added links to other languages in all READMEs, added some missing shield badges
Just updated all the READMEs to have links to other languages.
Noticed that some READMEs do not have certain badges or even logo to match the main README (english version), so added that. 

Added links to other languages in all READMEs, added some missing shield badges

---

docs/source/live.rst

- [-] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [-] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [-] I've added tests for new code.
Fixes a trivial typo and grammar I found in the live docs while using them.

Fix trivial typo and grammar in live docs

---

docs/source/traceback.rst

- Show how to create a `console` object
- Demonstrate the `show_locals=True` parameter
Refs #1380

Improved example code for trackback

---

.github/workflows/codespell.yml
README.cn.md
README.de-ch.md
README.de.md
README.es.md
README.fr.md
README.hi.md
README.ja.md
README.kr.md
README.md
README.pt-br.md
README.sv.md

Adds PT-BR (brazilian portuguese) README and related links to other README files.

Create Brazilian Portuguese readme

---

README.cn.md
README.de-ch.md
README.de.md
README.es.md
README.fr.md
README.hi.md
README.ja.md
README.kr.md
README.md
README.pt-br.md
README.sv.md

I've been working on a new translation and found it unnatural not having a link to go back to the English version of the readme, as it was a quick change I decided to propose instead of asking.

Adds the "English readme" link to all README.* files

---

tests/test_segment.py

All Enum changes were reverted from Python 3.10 just before rc1.  Revert
the test changes to fix test failures with 3.10.0rc1.

revert expected test_repr value for py3.10 following upstream

---

docs/source/markup.rst

Noticed when reading. Missing letter on “the”

Corrected typo in Console Markup docs.

---

docs/source/pretty.rst

Noticed when reading: “use” rather than “user”

Corrected typo in Pretty Printing docs.

---

rich/console.py

Was using this method, and noticed that the docstring was wrong. Didn't add myself to `CONTRIBUTORS.md`, because this change is so trivial.

Remove documentation for unknown argument from `Console.status`

---

docs/source/padding.rst

This I think is the minimum change here, to add the missing word. By this point in the docs, “in any context that accepts a string”, or similar is probably a bit much.

Corrected typo in Padding docs.

---

docs/source/progress.rst

The bar has ratio 2, taking up the “remaining two thirds”.

Corrected example description in Progress docs.

---

CHANGELOG.md
rich/__init__.py

(really not sure how to test this properly)
fix #1425

BUG: ensure the global _console object is initialized properly when rich.reconfigure is called

---

rich/_inspect.py

Fixes: when using `inspect(obj, docs=False)` the docstring is still being printed.

Bugfix: Don't print docstring in inspect() if docs is False

---

CHANGELOG.md
CONTRIBUTORS.md
rich/json.py

Add support for `rich.json` to read input from stdin (eg. pipes) when no file name is provided.

Add stdin support to rich.json

---

rich/table.py

Fix typos in `rich.table.Table` docstring

---

rich/console.py
tests/test_console.py

Replace hand-rolled html escape function with builtin `html.escape`.
Has the added benefit of escaping `"` with `&quot;` and `'` with `&#x27;`.
Also deleted a stray print in the test.

Use builtin html.escape

---

CHANGELOG.md
pyproject.toml
rich/pretty.py
tests/test_pretty.py

Fixes https://github.com/willmcgugan/rich/issues/1492

test fake attributes

---

CHANGELOG.md
docs/source/traceback.rst
examples/recursive_error.py
examples/suppress.py
pyproject.toml
rich/console.py
rich/pretty.py
rich/traceback.py
tests/test_traceback.py

Suppress frames and max_frames

---

rich/json.py

Literally just fix the docstring which says what the defaults are for json printing. For indent and highlighting, they're swapped around.

Fix swapped defaults in docstring for json printing

---

README.cn.md
README.de-ch.md
README.de.md
README.es.md
README.fr.md
README.hi.md
README.ja.md
README.kr.md
README.md
README.pt-br.md
README.sv.md

Updated the month that "Star Wars: The Rise of Skywalker" was released to be "Dec" from "Dev"; an understandable err given that every good month is "development" month. 😝

Fix misspelled month in readme table example

---

docs/source/style.rst

Remove extra space in `Theme` example.

Remove extra space in Theme example

---

CHANGELOG.md
rich/pretty.py

Fixes https://github.com/willmcgugan/rich/issues/1646

allow disable pprint

---

CHANGELOG.md
CONTRIBUTORS.md
rich/console.py
tests/test_rich_print.py

This PR adds `soft_wrap=True` to `print_json` to prevent the truncation of values longer than the width of the console.
- Fixes #1653

Set soft_wrap in console.print json  to prevent truncation

---

LICENSE

Wrap `LICENSE` file at 80 characters to make generated license reports from tools such as [`pip-licenses`](https://github.com/raimon49/pip-licenses) format better in horizontally limited spaces (e.g. HTML license report in the browser).
License text/wrapping is taken from the canonical MIT text on Wikipedia:
- https://en.wikipedia.org/wiki/MIT_License#License_terms

Wrap LICENSE file at 80 characters

---

rich/_log_render.py
tests/test_log.py

Some terminal emulators like iterm2, support anchoring to the line
number:
https://iterm2.com/documentation-one-page.html see Anchor (OSC 8)
section:
Note: in iTerm2 version 3.4 and later, if the URL has the file scheme and
a # fragment is present then the semantic history rules will apply
for opening the file. It may optionally include a line number, like
file:///tmp/file.txt#123 or line number and column number like
file:///tmp/file.txt#123:45
This update the logic in the logger so that the line number links the
the corresponding file on the same line.
As I'm not sure whether all terminals support that, I let the  clik on
the file name point to the file itself w/o line numbers.
And for discoverability and user friendliness the colon itself is
unstyled so that it's easier to discover …

Have logger link to proper file line.

---

CHANGELOG.md
rich/cells.py
tests/test_cells.py

Fixes https://github.com/willmcgugan/rich/issues/1682

fix infinite loop

---

rich/console.py

Missing backtick breaking reference in docs.

Fix broken pager reference

---

CHANGELOG.md
rich/console.py
tests/test_console.py

Special case for Text in print to allow use of sep. Fixes https://github.com/willmcgugan/rich/issues/1689

special case for Text

---

CHANGELOG.md
CONTRIBUTORS.md
docs/source/progress.rst
examples/dynamic_progress.py

- Is this required for examples too? If so, happy to look into it...
Additional example for progress bars, more dynamic in nature than the existing [live_progress.py](https://github.com/willmcgugan/rich/blob/master/examples/live_progress.py>); see also discussion in #1500 .
Screenshot while running:
Screenshot when done:

add example with dynamic group of progress bars

---

rich/cells.py

Change the spelling of sequece to sequence to fix the failing codespell test.

Fix failing codespell test

---

docs/source/live.rst

Improve the formatting by monospacing the following command:

Improve formatting of live command

---

CHANGELOG.md
CONTRIBUTORS.md
docs/source/text.rst
rich/text.py
tests/test_text.py

Add a simple little helper to run `AnsiDecoder.decode_line` over "pre-cooked" inputs.
Fixes issue: #1670

Add a Text.from_ansi helper method

---

CHANGELOG.md
pyproject.toml
rich/live.py

fix for deadlock

---

docs/source/logging.rst
rich/logging.py
tests/test_logging.py

This adds support for overriding the log highlighter per log message.
It also adds a test for the per log message markup and highlight overrides.

Per message log highlighting

---

Makefile
tests/test_console.py
tests/test_layout.py
tests/test_spinner.py
tests/test_tree.py

Sets _environ to empty dict so that CI environment doesn't change outcome of tests.
Fixes https://github.com/Textualize/rich/issues/1051

fix environment to empty in tests

---

rich/traceback.py

The traceback border styles were backwards. I flipped them. That's it.

Fix flipped traceback border styles

---

.pre-commit-config.yaml

Adds some other pre-commit hooks, adds config to ensure isort and black don't clash.

Let isort & black play together nicely, adds new hooks

---

CHANGELOG.md
rich/_windows.py
rich/traceback.py
tests/test_traceback.py

A `Theme` was instantiate to contain the styles used in the rendering of a traceback. This theme by default inherited the default styles, which in turn would override the user-supplied theme.

Theme used for Traceback should not inherit defaults

---

CHANGELOG.md
rich/console.py

RenderGroup has been renamed to Group

Render Group

---

CHANGELOG.md
rich/color.py
rich/palette.py
rich/progress_bar.py
rich/style.py
tests/test_bar.py

Reverts Textualize/rich#1834
In retrospect, this original behaviour was fine

Revert "Stop using functools.lru_cache decorator on instance methods"

---

CHANGELOG.md
rich/syntax.py

Syntax should always justify left

---

CHANGELOG.md
rich/syntax.py
tests/test_syntax.py

Adds ability to pass a lexer to Syntax.from_path

Allow override of lexer in Syntax.from_path

---

CHANGELOG.md
rich/_inspect.py
rich/default_styles.py
tests/test_inspect.py

Removes assumption that all callables should be prefixed with `def`/ account for classes in inspect().

Handle classes in inspect when methods=True

---

docs/source/tables.rst

The ```Column``` option ```no_wrap``` was documented accidentally as if it is a ```wrap``` option.
Updated the documentation to match actual behavior and the ```add_column``` docstring.

Tables - Column - Fix documentation of no_wrap option

---

.pre-commit-config.yaml
tests/test_traceback.py

A couple of weeks ago I changed this line of code because it was making the `no-eval` pre-commit hook fail. The test still passed because of the broad `except Exception` clause, but a SyntaxError was no longer being raised. This just reverts back and removes that pre-commit hook (I'm not aware of any means of having these hooks ignore a line).
```
rich/traceback.py          225      1    99%   386
```
Takes coverage of this file back from 93 to 99.
Fixes #1882

Traceback coverage

---

rich/progress.py
tests/test_progress.py

Added new default_columns() classmethod to the Progress class, so that client code does not need to replicate the defaults literally, but can just add `*Progress.default_columns()`

Add default_columns classmethod to Progress class

---

.coveragerc
.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
rich/diagnose.py

Adds `diagnose.report` function. Also adds some additional information from env vars if the user is using Jupyter, that might help convey what platform they're using if they don't specify in the bug report.
I've added the file as an omission to coverage reporting since it's only used for debug purposes.
```
╭──────────────────── <class 'rich.console.Console'> ─────────────────────╮
│ A high level console interface.                                         │
│                                                                         │
│ ╭─────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=93 ColorSystem.TRUECOLOR>                            │ │
│ ╰─────────────────────────────────────────────────────────────────────╯ │
│ …
```

Expose diagnose.report as a function

---

CHANGELOG.md
pyproject.toml
rich/measure.py

optimization for measure

---

CHANGELOG.md
CONTRIBUTORS.md
tests/test_inspect.py
tests/test_syntax.py

1. Fix test_syntax to compare strings via `==` rather than `is`, in order to fix test failure on PyPy3.
2. Skip a few test_inspect tests on PyPy3 that fail due to different output.

PyPy3 test fixes

---

docs/source/tables.rst

Just fixes a typo in the docs where two keyword arguments for the table class was missing an underscore.

Fix keyword argument names

---

CHANGELOG.md
CONTRIBUTORS.md
rich/jupyter.py

Closes https://github.com/Textualize/rich/issues/1905
I've yet not updated CHANGELOG.md since I do not know which version of rich with this pr ship with, nor when the version will be released. I have not updated CONTRIBUTORS.md since I do not think this is a significant contribution. If you want I can do those.

In Jupyter mode have the link target set to "_blank"

---

CHANGELOG.md
CONTRIBUTORS.md
rich/highlighter.py
tests/test_highlighter.py

This PR contains 2 changes:
1. enum.Flag supports more than one bit to be set, and it is displayed like `<Permission.READ|WRITE: 3>`. The `|` character was not recognised by ReprHighlighter as part of a tag_name, causing only the first part to be highlighted.
2. This is purely cosmetic, but I found the regexes to be really difficult to parse because of all the backslashes. Most of those actually weren't necessary, the commit explains the details further. However, this commit is completely optional.

Fix repr highlighter

---

rich/console.py

Document the need for `'{stylesheet}'` in the `code_format` arguments for `console.Console.export_html` and `console.Console.save_html` if `inline_styles` is set to `False` (the default). I'm not really happy with the wording here to be honest.

Document the need for '{stylesheet}' in `code_format` for HTML export

---

CHANGELOG.md
CONTRIBUTORS.md
rich/syntax.py

Changes default arg for lexer_name so 'default' doesn't override guessing.

Fix lexer guessing for rich.syntax cli.

---

rich/progress.py
tests/test_progress.py

While working on https://github.com/pypa/twine/pull/877, I noticed that `DownloadColumn` uses `KB` instead of `kB`, even though the divisor is 1000 (like `FileSizeColumn` and `TransferSpeedColumn`).

Use "kB" for `DownloadColumn`

---

CHANGELOG.md

The 10.16.2 entry in the changelog does not currently have a link associated with its header 🙂

Add missing 10.16.2 link

---

CHANGELOG.md
rich/pretty.py
tests/test_pretty.py

Fixes https://github.com/Textualize/rich/issues/1998

Fixes Pretty.__measure__ not respecting expand_all

---

CHANGELOG.md
CONTRIBUTORS.md
rich/progress.py
tests/test_progress.py

While [replacing Twine's progress bar with Rich](https://github.com/pypa/twine/pull/877), I got into some bike-shedding/yak-shaving to declutter the time column. After looking at several download progress indicators (e.g. Chrome, Firefox, `wget`, `scp`), it seems more common to show time remaining than time elapsed. Both `wget` and `scp` show time remaining until the download is finished, then switch to time elapsed. So, I implemented that behavior here.
For example:
https://user-images.githubusercontent.com/1326704/155128465-783d6866-006b-4e9c-bcae-45267b787e24.mp4

Add condensed time column

---

.github/workflows/pythonpackage.yml

[codecov action v1](https://github.com/codecov/codecov-action#migration-from-v1-to-v2) has been deprecated and it don't seems like it would be breaking change for rich.
Also updates `checkout` [action to v2](https://github.com/actions/checkout#whats-new)

Bump codecov-action (v1 is deprecated) and actions/checkout 

---

rich/_win32_console.py
rich/_windows.py
rich/console.py
tests/test_win32_console.py

Some fixes for the PR #1993
* Adds support for bold, dim, and reverse on legacy Windows consoles.
* Calls the Windows Console API in order to output text, instead of writing to the `Console.file`
* More docstrings

Add support for bold, dim, and reverse on legacy Windows consoles

---

CHANGELOG.md
rich/pretty.py
tests/test_pretty.py

Closes #2012 
Named tuples will be formatted similarly to dataclasses when formatted using the `pretty` module. The code for handling this is very similar to dataclasses, but I opted not to try and factor it out as I think it will reduce readability.

Add support for named tuples to pretty

---

CHANGELOG.md
rich/_win32_console.py
rich/_windows.py
rich/console.py
tests/test_win32_console.py

Fixes #2053 
Moves from Windows Console API for writing to stdout, to using stdout.write.
Also opens stdout directly as requested to avoid issues with wrapped file objects passed into Console.

Windows output capture fix

---

CHANGELOG.md
rich/cells.py

Use `reversed` instead of `[::-1]` to reverse in chop_cells

Use `reversed` instead of `[::-1]` to reverse in chop_cells

---

CHANGELOG.md
rich/text.py
tests/test_text.py

Fixes https://github.com/Textualize/rich/issues/2054

Add missing `end` keyword argument to `Text.from_markup`

---

rich/__init__.py
rich/traceback.py

Fixing over-cleaning from https://github.com/Textualize/rich/pull/2001. This is an intentional unused import, so using the appropriate noqa. Reran pycln to ensure it is working.
See https://github.com/Textualize/rich/pull/2001#issuecomment-1079102117

fix: keep pycln from removing load_ipython_extension

---

rich/repr.py

Another typing cleanup/fix pulled out from
https://github.com/Textualize/rich/pull/2084. By using `cls: Type[T]` instead of
`T`, MyPy becomes smarter about handling this and less type ignores are needed,
since the typing is more precise.

fix(types): use Type[T] instead of T for cls

---

pyproject.toml
rich/_lru_cache.py

Refactor to remove the workaround for https://github.com/python/mypy/issues/6904 - you can use `typing_extensions.OrderedDict` here on 3.6-3.8 (naturally supported 3.9+) and avoid the multiple inheritance & type ignore. From #2084.

refactor: remove mypy generics workaround

---

pyproject.toml
rich/color.py
rich/console.py
rich/pretty.py
rich/repr.py
rich/traceback.py

Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>
This adds type ignore codes to all type ignores, and activates the (new in MyPy
0.94x) feature to verify that all type ignores have error codes. Unlike
previous methods of requiring error codes (like pre-commit's pygrep hook), mypy
will actually tell you what the correct error code is in the error message,
which is quite nice for adding them.
Having the error codes improves the readability, since you get a hint as to why
the type ignore is there (actual human readable hint, unlike flake8's numeric
codes), and it also keeps one type ignore from hiding another problem. This was
used in the last few PRs to see type ignores that were pretty easy to work
around.

chore(types): include error code on type ignores

---

CHANGELOG.md
docs/source/progress.rst
examples/cp_progress.py
examples/file_progress.py
examples/save_table_svg.py
pyproject.toml
rich/console.py

Refinement to docs re new progress bar feature, and new examples.

Progress docs

---

CHANGELOG.md

Fix date in CHANGELOG
Fixing the date in the CHANGELOG. It's currently April, which is the 4th month. (The incorrect date had month 5, which is May... that's next month.)

Fix date in CHANGELOG

---

CHANGELOG.md
CONTRIBUTORS.md
rich/console.py
tests/test_console.py

This fixes the "pipe" bug, where we could not determine the available size correctly when the output of Rich is piped to another process
This should (:crossed_fingers:) fix this bug: https://github.com/Textualize/rich/issues/2154

Fall back to `sys.__stderr__` on non-Windows OS to get size

---

rich/__init__.py
rich/_console.py
rich/_export_format.py
rich/console.py
tests/test_console.py

The name of the font and the ID of the wrapper we use for the generated SVG code are now dynamic, and their default value contain "rich" in order to avoid conflicts with people's own resources if they embed such generated SVGs in an HTML page.
All the CSS selectors are also prefixed with the ID of the wrapper now, which should isolate then from the other ones defined in a surrounding HTML page.
Issue: https://github.com/Textualize/rich/issues/2147
On this annotated screenshot we can see this namespacing in action:

[console] namespace SVG elements to avoid conflicts with surrounding HTML page

---

docs/source/progress.rst
rich/progress.py
rich/progress_bar.py
tests/test_progress.py

With this PR we now render a "pulse" progress bar when the given `total` is None. 
Which is a new possibility we now have: this parameter used to be a `float`, and is now an `Optional[float]` - so it shouldn't bring any compatibility issues, as the type is just widened to a value that was not accepted according to the documentation, and which would raise exceptions before if it was used?
To carry the semantic of _"we don't know the 'total' value for my progress bar"_, instead of `None` we could have used other kinds of values, such as:
- A negative value, like `total=-1`. The benefit would have been that the signature would still have been `float` , but the drawback is that the meaning of this value is less clear when debugging
- A sentinel value, such as …

[progress] The `total` we pass to a Progress renderable can now be `None`

---

CHANGELOG.md
rich/file_proxy.py
tests/test_file_proxy.py

Fixes https://github.com/Textualize/rich/issues/2047

Fix recursion error in Jupyter

---

pyproject.toml
rich/console.py
rich/jupyter.py
rich/measure.py
rich/pretty.py
rich/progress.py
rich/spinner.py
rich/style.py
rich/tree.py

This enables a few extra mypy checks, and fixes type bugs exposed by those. There were three features enabled, but I've left one off: `warn_unrachable = true`. While it is really useful, and helped expose a couple of the issues fixed here, it also requires type ignoring in about 5-7 places unavoidably, so I've left it off. The most irritating one is `if sys.platform.startswith("win")` constructs, which it will notice are unreachable if you are typing targeting a different platform. MyPy might fix this in https://github.com/python/mypy/issues/12286, which would run all platforms/versions in parallel and then combine the results (which would be really fantastic!), but until then, it's likely better just to manually add `--warn-unreachable` once in a while and make sure the errors reported …

fix(types): typing fixes exposed by extra checking

---

CHANGELOG.md
rich/progress.py
tests/test_progress.py

Adds a `show_speed` parameter to `TaskProgressColumn` which displays speed in iterations per second when the total is not known in advance.

progress speed

---

rich/__init__.py

Fixes https://github.com/Textualize/rich/issues/2197

fix import cwd if no cwd

---

CHANGELOG.md
rich/traceback.py
tests/test_traceback.py

It turns out that we intentionally don't add such a whitespace at the beginning of the trace rendering, but we were actually doing so for the 2nd item of the stack rather than the 1st one
closes #2206 
We can see a blank line before the 1st frame of the stack, and a missing blank line before the 2nd one:
The 2nd frame is now properly displayed with a blank line before it, while the 1st frame starts right away at the beginning of the Panel:

[traceback] Fix "missing whitespace" bug

---

CHANGELOG.md
rich/traceback.py
tests/test_traceback.py

[traceback] Add traceback frame opt-out via a `_rich_traceback_omit = True` machinery

---

rich/console.py

The default width is now 100, not 88.

console: Update docstring for print_exception

---

CHANGELOG.md
rich/live.py

Without this the user sees no error displayed in their terminal - and even capturing the exception and displayed their own error reporting is ineffective.
fixes #2291

[live] Restore `sys.stderr` when an exception happens during a refresh

---

CHANGELOG.md
pyproject.toml
rich/_inspect.py
rich/control.py
rich/text.py
tests/test_control.py
tests/test_inspect.py

:warning: This PR introduces a (minor) breaking change, in order to fix a (minor) issued described with the screenshots below. :point_down: 
But we can of course choose to keep the existing behaviour as-is instead :slightly_smiling_face: 
As reported [there](https://github.com/Textualize/rich/issues/2284), running this command was making Rich crash:
```py
python3 -c "import pyparsing; from rich import inspect; inspect(pyparsing, methods=True)"
```
It took me a while to understand what was going wrong, as the code from which the exception pops is in `Text.divide(offsets)` which is quite a complex part :exploding_head: 
But in the end I identified the culprits :ninja: : special ASCII characters! (in docstrings)
We were removing them from the content of the textual content of the `Text` …

[bugfix] solve crash when using `inspect()` on the "pyparsing" package

---

docs/source/progress.rst

- [] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [] I've added tests for new code.
The basic example for progress was a little confusing and wouldn't run. It now can be copy-pasted and run to demonstrate the feature.

Turn "basic usage" progress example into a runnable example

---

CHANGELOG.md
rich/progress.py
tests/test_progress.py

Hi all!
This is just a quick follow-up patch for file/progress so that the reader takes the `name` attribute from the internal handle. Currently, the `_Reader` has a `name` attribute (inherited from `RawIOBase`) but it's always `None`.

Forward the internal handle name wrapped in `rich.progress._Reader`

---

CHANGELOG.md
rich/_win32_console.py
tests/test_win32_console.py

By doing this the users get their original cursor style back when Rich gives control back to the terminal, rather than a "full size" one
Fixes #2333 
We can see the cursor is no longer the same (converted to a "thick" one) after Rich gives control back to the terminal:
https://user-images.githubusercontent.com/722388/173618989-275d0802-fc29-4830-8c19-e63bd3c9b401.mp4
Cursor-after-Rich is well and truly the same than cursor-before-Rich:
https://user-images.githubusercontent.com/722388/173619377-9db1605d-a6fb-4df2-aad4-a50b4b873a69.mp4
(I also tested with Powershell, and the fix looks to work there too :-)

[win32] Use initial cursor size when hiding or showing it

---

CHANGELOG.md
rich/_lru_cache.py
rich/cells.py
rich/style.py
tests/test_lrucache.py

Fixes a performance bug in the Style class.
Essentially the hash calculation was inconsistent. Things that were equal would sometimes have different hashes. I noticed this when adding `lru_cache` to `Style.__add__`. What should have been an easy win caused dramatically reduced performance, because it broken the mechanics of storing Styles in a dict.
The hashing is now in once place. It is also lazy, so the hash is stored the first time it is used.

Fixed Style hash

---

rich/rule.py
tests/test_rule_in_table.py
tests/test_spinner.py

WIP fix for issue #2266 (`Rule` in `Table` doing weird things to column widths).
@willmcgugan suggested adding a `Rule.__rich_measure__()` method returning `Measurement(1, 1)` — and that does indeed fix the cases identified in the issue.
*Unfortunately* it seems to interact weirdly with `Spinner`; in particular the `test_spinner_update()` test hangs indefinitely on [this line](https://github.com/Textualize/rich/blob/master/tests/test_spinner.py#L53=):
```python
spinner.update(text=Rule("Bar"))
```
All other tests are passing OK with this change.
I'm unsure how to proceed so opening this PR for further discussion.
**I've marked that hanging test with `pytest.skip()` in this branch** so all tests pass but it's not yet ready to be merged, in fact.

Add Rule.__rich_measure__ and tests vs behaviour in tables

---

CHANGELOG.md
CONTRIBUTORS.md
docs/source/console.rst
rich/console.py
rich/diagnose.py
tests/test_jupyter.py

I'm opening this is a very small PR just to get initial feedback on whether it sounds like a good idea. If the response is positive then I will update tests as required.
`COLUMNS` and `LINES` environment-variables can already be used to set `Console._width` and `Console._height`: https://github.com/Textualize/rich/blob/51889e2e663bbda8d59b2a68f23322f578681cea/rich/console.py#L676-L683
However, these environment variables are ignored when using Jupyter. If `width` or `height` are not explicitly set in `__init__`  then rich assumes default values: https://github.com/Textualize/rich/blob/51889e2e663bbda8d59b2a68f23322f578681cea/rich/console.py#L658-L660
This PR makes it so that `COLUMNS` and `LINES` can be used to set `Console._width` and `Console._height` even when  `self.is_jupyter` is …

Allow Jupyter to vary width/height using COLUMNS/LINES

---

CHANGELOG.md
rich/_inspect.py
rich/default_styles.py
tests/test_inspect.py

Adds a feature to prepend `async def` when `rich.inspect` is used on a 3.5+ style coroutine function, as demonstrated in the below screenshot.
3.4-style generator-based coroutines are left as-is.

Prepend "async def" to Inspect coroutine functions

---

rich/cells.py

Makes `cached_cell_len` public.
This is primarily for Textual which will need to get the `cell_len` of generally small segments.

added cached_cell_len

---

rich/progress.py

- [x ] I accept that @willmcgugan may be pedantic in the code review.
* Added missing `visible` and `description` missing in docstring of `Progress.reset`
* Corrected typo in docstring of `add_task`

Added missing args in docstring of Progress.reset

---

rich/logging.py

Add `Args:` to docstring of `render_message` so that https://rich.readthedocs.io/en/stable/reference/logging.html#rich.logging.RichHandler.render_message looks nice.

Add missing `Args:` to docstring

---

.github/workflows/pythonpackage.yml
Makefile
pyproject.toml
rich/color.py
tests/test_inspect.py
tests/test_pretty.py

* Tests Rich against Python 3.11.0-beta4
* There are issues with `pytest-cov` on 3.11 only. I'm going to minimally reproduce them and, if I can, report it to the pytest team. For now, coverage doesn't run on 3.11, but will continue to run on other versions.
* There were 5 test failures that have been resolved.

Add Python 3.11.0-beta4 to CI

---

.github/workflows/pythonpackage.yml
CHANGELOG.md
rich/console.py

The "no_color" parameter of Console was not being respected on legacy Windows mode.
This update strips colour from the Segment buffer if necessary, before passing them into the legacy Windows renderer.
Also updates to Python 3.11b5 (up from b4) in CI.

Handle 'no_color' Console on legacy Windows platforms

---

rich/pretty.py
tests/test_pretty.py

Closes #2485
One thing not discussed in the issue was how to deal with more complex types like dataclasses and namedtuples. So far I'm treating them the same as dicts and lists. In other words, the delimiters stay the same as if we weren't abridging anything, but the children are replaced with `...`. For example: `"{'unit': StockKeepingUnit(...)}"`

Add delimiters to elided pretty prints

---

CHANGELOG.md
CONTRIBUTORS.md
rich/pretty.py
tests/test_pretty.py

Add max_depth arg to install()

---

tests/render.py
tests/test_markup.py
tests/test_traceback.py

A couple of the escape sequences in strings are causing DeprecationWarning in the test suite
```
tests/test_markup.py:147
/Users/wim/git/rich/tests/test_markup.py:147: DeprecationWarning: invalid escape sequence '\['
result = str(render("[dim white]\[url=[/]"))
tests/test_traceback.py:52
/Users/wim/git/rich/tests/test_traceback.py:52: DeprecationWarning: invalid escape sequence '\.'
"^│ .+rich/tests/test_traceback\.py:",
```

fix invalid escapes

---

CHANGELOG.md
CONTRIBUTORS.md
rich/progress.py
tests/test_progress.py

Add the missing `mode` property to the file wrapper used by `rich.progress.wrap_file`.
This fixes an incompatibility with the [requests](https://github.com/psf/requests) library.
Without this property, uploads using `requests` fail to set the `Content-Length` header, and fall back to chunked encoding,
which many hosts (e.g. S3) don't support.
`requests` uses the `mode` property in its
[`super_len`](https://github.com/psf/requests/blob/177dd90f18a8f4dc79a7d2049f0a3f4fcc5932a0/requests/utils.py#L151)
function, which determines the length of the stream to upload.
```python
def upload_stream(session: requests.Session, source: BinaryIO, remote_url: str, size: int, label: str):
"""Upload a data stream from `source `to `remote_url``."""
with wrap_file(source, size, description=label) as f: …
```

Fix missing `mode` property on file wrapper

---

CHANGELOG.md
CONTRIBUTORS.md
rich/console.py

Detect Databricks as Jupyter environment, although it is kind of a weird breed of Jupyter Notebook. This should make `JUPYTER_LINES` and `JUPYTER_COLUMNS` configurations useful for Databricks
Added a condition to check for Databricks environment variable. Fix #2422

Detect Databricks as Jupyter environment

---

CONTRIBUTORS.md
rich/traceback.py

Exceptions from subprocesses raised by 'multiprocessing' don't include a traceback, so rich doesn't currently print them. They contain important information though, so this PR enables printing the exception without the traceback. This works because `walk_tb` doesn't do anything if the input is `None`.
Minimal example:
```py
import rich.traceback
import multiprocessing
def fail():
raise ValueError
if __name__ == "__main__":
rich.traceback.install()
with multiprocessing.Pool() as pool:
pool.apply(fail)
```
Note that exceptions from multiprocessing include the traceback formatted as a string in the description of the exception (see this code in multiprocessing.pool: https://github.com/python/cpython/blob/main/Lib/multiprocessing/pool.py#L57). This will be printed by rich after this PR.

Print cause of exceptions even when they have no traceback

---

rich/__init__.py

Update the docstring for `rich.reconfigure`. Previously, the docstring said it would accept an instance of `rich.console.Console`, but it expects positional and keyword arguments that are forward to the initializer for `rich.console.Console`.

docs: update `rich.reconfigure` docstring

---

rich/__init__.py

I didn't run Black, added tests, nor updated the other files, because this update is just like a few characters long of code (check the diff in "Files changed")
PR details:
"When I import print_json i get an underline in PyCharm because print_json is not listed in the __all__ of the init.py module.
Please add it so that IDE's don't complain."
This PR adds print_json function to __all__ in __init__.py

Solves issue #2464: Add print_json to __all__ in __init__.py

---

CHANGELOG.md
rich/console.py

Exposes font_aspect_ratio as a parameter on export_svg and save_svg rather than hardcoding 0.61.
This is for users who would like more control over the rendering to accomodate different fonts used in their format string.

Expose font_aspect_ratio as parameter on SVG export

---

CHANGELOG.md
rich/layout.py

The height parameter wasn't used.

Remove unused height parameter from Layout class

---

rich/console.py
tests/test_console.py

As part of Airflow's CI we save SVG images of our command's help output and commit them to git.
Without this change a single character change in the help text results in every single class and id in the SVG changing, which makes the diffs unreadable.
This adds an option for us to be able to specify a fixed prefix so that our git diffs are minimized.
(I also tided up the help docstring for export_svg and save_svg which didn't match signature any more)

Add support for specifying (persistent) id for SVG exports

---

CHANGELOG.md
docs/source/tables.rst
rich/table.py
tests/test_table.py

Added `Table.add_section` to add a new section.
Fixes https://github.com/Textualize/rich/issues/2478
Fixes https://github.com/Textualize/rich/issues/2477
Fixes https://github.com/Textualize/rich/issues/2476

sections docs and test

---

CHANGELOG.md
rich/syntax.py
tests/test_syntax.py

fix for syntax measure

---

.github/workflows/pythonpackage.yml

There is an issue with the latest version of this action, that's specific to Python 3.8 on Windows. Pinning to the (as of the time of writing) last-but-one version lets out tests work again.
See #2568.

Clean version of the temporary pin of snok/install-poetry

---

.github/workflows/pythonpackage.yml
CHANGELOG.md
README.md
poetry.lock
pyproject.toml
rich/_null_file.py
rich/highlighter.py
rich/rule.py
tests/test_null_file.py

Implements the requirements outlined in #2566.

Drop Python 3.6 as the minimum-supported Python version

---

CONTRIBUTORS.md
rich/pretty.py
tests/test_inspect.py
tests/test_pretty.py
tests/test_repr.py
tox.ini

- [n/a] I've added tests for new code.
Follow on from https://github.com/Textualize/rich/pull/2567, remove some redundant code now support for EOL Python 3.6 has been dropped.

Remove redundant Python 3.6 code

---

.github/workflows/codespell.yml
pyproject.toml

It was still pointing to the older location within Will's GitHub, but now it lives under the Textualize organisation.

Update the homepage in pyproject.toml

---

rich/spinner.py

Move the `rich.spinner.Spinner` docstring from the method `__init__` to the class so that the [reference docs page](https://rich.readthedocs.io/en/stable/reference/spinner.html) isn't empty.

Move spinner docstring to class.

---

CHANGELOG.md
CONTRIBUTORS.md
rich/pretty.py

I added the type annotation `str` for `pretty.Node.key_separator`, which is a dataclass that should have its attributes annotated. Otherwise, Python treats the unannotated attributes as class attributes.

Add the type annotation `str` for `pretty.Node.key_separator`

---

CHANGELOG.md
rich/_fileno.py
rich/console.py
tests/test_getfileno.py

More robust handling of `fileno()` which is often implemented badly in proxies and wrappers.
Should fix https://github.com/Textualize/rich/issues/2645

robust handling of fileno

---

CHANGELOG.md
rich/_export_format.py
tests/test_console.py

I've reversed the `pre` and `code` tags in the base HTML format. Otherwise it looks like the browser terminates the first code tag early, wraps it in a `p`, and then re-uses `code` in the `pre` tag :confused:  
PRE:
> The PRE element tells visual user agents that the enclosed text is "preformatted". When handling preformatted text, visual user agents:
>
> May leave white space intact.
> May render text with a fixed-pitch font.
> May disable automatic word wrap.
> Must not disable bidirectional processing.
CODE:
> Designates a fragment of computer code.

Update HTML format (reverse pre and code tags)

---

CHANGELOG.md
CONTRIBUTORS.md
rich/progress.py

This PR changes `progress.track` to use `operator.length_hint` (which calls `__len__` if exists, or `__length_hint__`) instead of `len()` when total is not provided. Allowing most built-in iterators and external library objects implementing the protocol with known length to have accurate progress tracking (such as `range` and `reversed`).
`operator.length_hint` was added in Python 3.4 as [PEP 424](https://peps.python.org/pep-0424/)
Other progress libraries, such as `tqdm`, already use this method:
https://github.com/tqdm/tqdm/blob/6791e8c5b3d6c30bdd2060c346996bfb5a6f10d1/tqdm/contrib/concurrent.py#L61

Use `operator.length_hint` to estimate progress total

---

CHANGELOG.md
rich/segment.py
tests/test_segment.py

Fixes an issue where splitting a string with mix cell lengths results in the wrong pair of Segments.

fix issue splitting segments

---

docs/source/progress.rst

Link format string in docs to Python string formatting mini-language

---

docs/source/layout.rst

Noticed a missing import while reading through the docs, drive-by PR.

add missing import to doc example

---

README.fa.md
README.id.md
README.md
README.ru.md
README.tr.md

In the README.md the py versions badge referenced an old rich version (10.11.0), which still supported py36, but rich doesn't support py36 anymore. Also py3.11 support was added since then.
I fixed this in all READMEs which included the py versions badge. (not all of them do)

update supported py versions badge

---

CHANGELOG.md
rich/pretty.py
tests/test_pretty.py

Fixes https://github.com/Textualize/rich/issues/2819

fix for empty dataclass

---

README.id.md

There's typo in the spelling of "penghilightan".

fix: Typo in the Indonesian readme doc

---

CHANGELOG.md
CONTRIBUTORS.md
rich/console.py
tests/test_console.py

#2449 caused FORCE_COLOR to forcefully imply a terminal. This environment variable tends to be set in a Jupyter context. When `Console.is_terminal` is True, duplicate output is produced by progress bars (#2740). I haven't tracked down exactly what output when `is_terminal=True` causes the duplicated output (likely something involving carriage returns or control characters, which Jupyter doesn't _always_ get right), but the fact remains that if you're in a Jupyter kernel, you aren't in a terminal.
This PR shifts the handling of FORCE_COLOR away from `_force_terminal` and into `is_terminal`, where other interactive environment detection happens (idle).
Sample output from b89d0362e8ebcb18902f0f0a206879f1829b5c0b:
closes #2740

Fix duplicate progress output in Jupyter

---

CHANGELOG.md
CONTRIBUTORS.md
rich/traceback.py

i took note that the traceback install code pre-dates the support for `stderr=True` and used `file=sys.stderr`
i believe its more correct to use `stderr=True` (coming from a pytest point of view where accidental install in code under test would lead to the handler eventually having a stale file)

use stderr=true instead of file=sys.stderr for traceback handler install

---

README.pt-br.md

Learned today that rich has README files in other languages (from a tweet about polish, I believe) and decided to read the pt-BR version. Spotted a few typos, so prepared this PR. Thanks!

Fix typos in pt-BR README

---

rich/pretty.py
tests/test_pretty.py

More context [in #2803](https://github.com/Textualize/rich/issues/2803#issuecomment-1427886362), but the IPython formatter spec expects slightly different behavior than the hook currently in `rich.pretty`. In particular:
1. formatters should _return_ their output, not publish it on a side channel, and
2. registered formatters should not gate their behavior on what other formatters may be registered
From looking through the code, I think these two are related, because when multiple formats are produced in a mimebundle, a Jupyter frontend displays only one. But because the IPython hook _printed_ output instead of returning it, it was always _in addition to_ other reprs - making it necessary to check if it was probably going to be the only one. Following the spec and returning output removes …

match expected IPython formatter spec in rich.pretty

---

pyproject.toml
tests/test_syntax.py

Relax our dependancy on Pygments.  To address issues like these:
Fixes https://github.com/Textualize/rich/issues/2810
Not our fault, per se. But that doesn't mean we aren't going to keep getting issues about it.

relax tests for old pygments

---

CHANGELOG.md
CONTRIBUTORS.md
tests/test_cells.py
tests/test_pick.py

It seems that `test_cells` misses some inputs like boundary cases. Those are important to avoid regressions. I updated `test_cell_len_long_string` and created `test_cell_len_short_string` to overcome this possible issue.
Also improved `test_pick`to cover untested inputs of `pick_bool`.

improving tests in test_cells and test_pick

---

CONTRIBUTORS.md
README.fr.md

- [X ] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [X ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [X ] I've added tests for new code.
- [X ] I accept that @willmcgugan may be pedantic in the code review.
I've edited the French translations which had a lot of errors. Some of them were important to understand properly (such as line 71, a bad usage of the verb être/be).

FRENCH FIXES

---

CHANGELOG.md
rich/console.py
tests/test_console.py

Fixes `FORCE_COLOR` not being respected.
Fixes https://github.com/Textualize/rich/issues/2859

fix for is_terminal

---

CHANGELOG.md
rich/text.py
tests/test_panel.py
tests/test_text.py

The `Text.extend_tabs` method was previously not taking in to account the spans.  Basically it would replace tabs with unstyled spaces. This resolves that issue by extending the style(s) on the tab to cover the new space characters

Extend tabs with styles

---

CHANGELOG.md
rich/markdown.py
tests/test_markdown.py

Fixes https://github.com/Textualize/rich/issues/3053

fix for markdown table

---

.pre-commit-config.yaml
CHANGELOG.md
rich/_export_format.py
tests/test_console.py

This PR fixes the HTML export template, addressing the issue raised in #3021
In doing so there's also an update to the pre-commit configuration (without it I wasn't able to commit the change -- the update is stolen from the same config file in Textual).

Fix the HTML export template

---

CHANGELOG.md
CONTRIBUTORS.md
rich/repr.py
tests/test_repr.py

When `repr`ing classes that have overwritten `__eq__` as parameters, the check with `== Parameters.empty` can be `True`.
Fixes #2875 with the suggested change. Also added the sample code as a test.

Fixed issue with custom classes (fixes #2875)

---

CHANGELOG.md
rich/pretty.py

Fixes https://github.com/Textualize/rich/issues/3013

Fix iPython breakage

---

CHANGELOG.md
CONTRIBUTORS.md
rich/highlighter.py
tests/test_highlighter.py

Allow tilde in URL (fixes #3057)

---

CHANGELOG.md
rich/markdown.py
tests/test_markdown.py

The table data elements were not interacting well with inline styles (in the rich sense) and the table data element would have its content overridden every time we found another excerpt of text with a different style.
The fix was to do something similar to what `TextElement` does in its method `on_text`, which is to append the new content instead of replacing it.
This fixes #3115.

Fix markdown table rendering issue with inline styles/links

---

CHANGELOG.md
rich/panel.py

This was such a quick fix that while triaging I thought I may as well just fix it.
Fixes #3142.

Add missing Panel.fit parameters

---

CHANGELOG.md
rich/prompt.py

Fix typing for `FloatPrompt` from `class FloatPrompt(PromptBase[int]):` to `class FloatPrompt(PromptBase[float]):`.

Fix typing for FloatPrompt

---

CHANGELOG.md

Time moves much faster than it has any right to nowadays, and sometimes we're caught unaware by the flipping of the calendar. While 2023 is objectively a much more interesting number, I *think* this was meant to be 2024.

chore(changelog): fix release date for 13.7.1

---

CONTRIBUTORS.md
rich/color.py
rich/console.py
rich/syntax.py
rich/traceback.py

We're investigating slow CLIs over at Typer: https://github.com/tiangolo/typer/discussions/744.  More generally, I am interested in improving Python import performance.
This PR cuts rich import time from ~230ms -> ~130ms on my machine.  Here's the test process.
Create a simple test script that mimics the dependencies used by Typer:
```python
from rich import box
from rich.align import Align
from rich.columns import Columns
from rich.console import Console, RenderableType, group
from rich.emoji import Emoji
from rich.highlighter import RegexHighlighter
from rich.markdown import Markdown
from rich.padding import Padding
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich.theme import Theme
```
Refer to: …

feat: speedup import time using sys.platform

---

CHANGELOG.md
CODE_OF_CONDUCT.md
rich/panel.py

Fixes https://github.com/Textualize/rich/issues/2745
Respects styles from Text objects

fix for panel title

---

CHANGELOG.md
rich/default_styles.py

Fixes #2825 by changing the default color of `'logging.WARNING'` to yellow.

Update "logging.level.warning" to yellow"

---

CHANGELOG.md
rich/pretty.py
tests/test_pretty.py

Fixes #2863
Add new function `_get_braces_for_deque` to respect `maxlen` for `collections.deque`.
Add tests for `pretty_repr` with non-empty and empty `deque`.

fix: fix `pretty_repr` for `deque`

---

tests/test_box.py

Improving `test_box_substitute` to cover more inputs of `substitute()`, like legacy_windows and ascii encoding. I believe this is important to avoid regressions.
Also refactored `test_box_substitute` to reduce its size: smaller and focused tests are better than large ones. We have now three tests: 
- test_box_substitute_for_same_box
- test_box_substitute_for_different_box_legacy_windows
- test_box_substitute_for_different_box_ascii_encoding

improving test_box_substitute to cover more inputs of substitute()

---

rich/logging.py
rich/traceback.py

https://github.com/Textualize/rich/issues/2795
add code_width option for traceback
``` python
from rich.traceback import install
install(
width=120,
code_width=120, # new option
word_wrap=True,
)
```
or
```python
import logging
from rich.logging import RichHandler
logging.basicConfig(
handlers=[
RichHandler(
rich_tracebacks=True,
tracebacks_code_width=120, # new option
)
],
)
```
before
after

add code_width in traceback

---

CHANGELOG.md
rich/progress.py
tests/test_progress.py

Ensure progress track thread closes on error

exit track thread

---

README.md

Just noticed the links were dead. I do remember there being a gallery at some point though.

rm broken links from README

---

rich/align.py
rich/panel.py
rich/tree.py

This pull request adds docstrings to missing arguments I have noticed in `panel.py` and `tree.py`.
Please review and merge when ready. Thank you!

Supplemented missing docstrings

---

rich/table.py

Defaults to the value of the self.table when the default value of None is unchanged.
It seems like the Column constructor didn't receive a `highlight` value, so I guess that it used to receive a highlight value at a later point. Someone who knows the project better could comment on that.
-> New feature
This is more of a proof of concept than an actual pull request.

Enable per-column enabling or disabling of highlighting

---

.pre-commit-config.yaml

Small change to the `pre-commit-config.yaml` file. I updated the image to`https://github.com/psf/black-pre-commit-mirror` and bumped the version to the latest,  as per Black's docs [suggestion](https://black.readthedocs.io/en/stable/integrations/source_version_control.html). 
As this is more of a dev tools update I wasn't sure if this warranted adding to `CHANGELOG.md`. Same goes for the tests, beyond checking pre-commit runs as expected.

use mypyc compiled black and update verison

---

rich/progress.py

This commit introduces a new 'completed' parameter to the 'track' function in order to support resumable progress. Now users can specify the starting point for progress, making it easier to implement progress resumption.
Add 'completed' parameter to 'track' function for resumable progress.

Add 'completed' parameter to 'track' function for resumable progress

---

README.md

A tiny correction: _OS X_ was renamed to _macOS_ in 2016.

docs: rename OS X to macOS

---

rich/tree.py

Run black over recent changes to `tree.py`. This is currently causing PR checks to fail.

style(tree): format with black

---

CHANGELOG.md
rich/console.py

Fixes #3419.
According to the [Highlighting docs](https://rich.readthedocs.io/en/stable/highlighting.html): 
> If you disable highlighting on the [Console] constructor, you can still selectively enable highlighting with `highlight=True` on print / log.
Unfortunately it looks like this hasn't worked since Rich v9.5.0! I am assuming this is a bug rather than an intentional change, but if that's the case then the documentation should be updated.

fix(console): fix selective enabling of highlighting

---

CHANGELOG.md
rich/console.py
tests/test_console.py

Handle BrokenPipe exceptions
Fixes https://github.com/Textualize/rich/issues/1591
Thanks to @lmmx for doing the legwork.

handle broken pipe

---

CHANGELOG.md
rich/console.py
tests/test_console.py

Fix https://github.com/Textualize/rich/issues/2563

Fix record and capture

---

CHANGELOG.md
rich/text.py
tests/test_text.py

Fixes https://github.com/Textualize/rich/issues/3014

Fixed exception in append_tokens

---

rich/highlighter.py
tests/test_highlighter.py

Fixed the bug [#3327](https://github.com/Textualize/rich/issues/3327).
Changes -
1. Added '@' in rich.highlighter:ReprHighlighter url regex pattern.
2. Added a test case in test_highlighter for the url with '@'.
Poetry installed black v22.12.0 and its formatting differs a bit from the latest version v24.8.0. Hence I've formatted with the prior to keep it consistent.

Fix [BUG] @ breaks highlighting in hyperlink #3327

---

CHANGELOG.md
rich/pretty.py
tests/test_pretty.py

Fixes https://github.com/Textualize/rich/issues/3417

fix for missing field in dataclass

---

CHANGELOG.md
rich/text.py
tests/test_text.py

Fixes https://github.com/Textualize/rich/issues/3479

fix infinite loop in append

---

.github/workflows/pythonpackage.yml
CHANGELOG.md
pyproject.toml
tests/test_pretty.py
tox.ini

The final Python 3.13 release candidate is out now! :rocket:
The Release Manager has issued a [call to action](https://discuss.python.org/t/python-3-13-0rc2-3-12-6-3-11-10-3-10-15-3-9-20-and-3-8-20-are-now-available/63161?u=hugovk]):
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.13 compatibilities during this phase, and where necessary publish Python 3.13 wheels on PyPI to be ready for the final release of 3.13.0. Any binary wheels built against Python 3.13.0rc2 will work with future versions of Python 3.13. As always, report any issues to [the Python bug tracker](https://github.com/python/cpython/issues).
This PR adds 3.13 to the CI and tox, and fixes a test that fails on 3.13.

Add support for Python 3.13

---

CHANGELOG.md
rich/segment.py
tests/test_segment.py

Fixed `Segment._split_cells` issue discovered in https://github.com/Textualize/textual/issues/4996

fix split cells

---

CHANGELOG.md
pyproject.toml

Fixes https://github.com/Textualize/rich/issues/3511

depenency fix

---

docs/source/tables.rst

While investigating an issue with the table, I noticed that the column `highlight` option was missing in the documentation.

docs(table): add column highlight option

---

CHANGELOG.md
rich/table.py
tests/test_table.py

Fixes #3517. The default value for the `Column.highlight` is False, so where necessary columns are added by the `add_row` method this should default to the `Table.highlight` value.

fix(table): highlight columns added by add_row

---

.readthedocs.yml
README.md
pyproject.toml
tests/test_inspect.py
tests/test_pretty.py
tests/test_repr.py
tox.ini

Some Python 3.7 leftovers remained when support for Python 3.7 was dropped in https://github.com/Textualize/rich/releases/tag/v13.9.0.
This completes the drop. Eg. PyPI still shows support for `3.7`.

Drop Python 3.7 leftovers

---

CHANGELOG.md
pyproject.toml
rich/segment.py
tests/test_segment.py

Fixes https://github.com/Textualize/textual/issues/5090

Segment.split_cells fix

---

CHANGELOG.md
pyproject.toml
rich/cells.py
rich/segment.py
tests/test_cells.py
tests/test_segment.py

Fixes an issue with the regex used to select the fast path for strings with single-width characters.
This may have had a detrimental effect on performance for some operations.

Regex error

---

.pre-commit-config.yaml
CHANGELOG.md
docs/source/console.rst
rich/console.py
rich/diagnose.py
tests/test_console.py

Implement new `TTY_COMPATIBLE` environment variable
@ofek @webknjaz @hugovk 
Relevant discussion: https://github.com/Textualize/rich/issues/2924

TTY_COMPATIBLE

---

rich/default_styles.py
rich/traceback.py

Prevent code highlights in exceptions from highlighting indentation. Previously indentation was underline, which didn't look good.

Don't underline indentation

---

CONTRIBUTORS.md
rich/style.py

The screenshot below shows how the leftover code got missed on commit 092cfa4d723a626b7e57c5ff163cfdce287ffc25

Remove leftover code from previous commit

---

CHANGELOG.md
rich/default_styles.py
rich/traceback.py

Adds support for exception groups

exception groups

---

rich/table.py

in `rich.table`, when executed as a main script, it imports `Table` from itself.
this seems unnecessary, considering the `Table` class is implemented in the same module.
this isn't only cosmetic though - at least one type checker (Pyre) gets confused because of this, and treats `Table` as a symbol that isn't exported by `rich.table`.
please let me know if this change is acceptable, and if so, whether it needs a CHANGELOG entry and/or additional tests.

Remove unnecessary import that confuses type checkers

---

docs/source/conf.py

Fix the documentation search not working after a recent Read the Docs upgrade.
This adds `sphinx_rtd_theme` to the extensions as recommended in the install guide: https://sphinx-rtd-theme.readthedocs.io/en/stable/installing.html
Fixes: #3697

docs: fix search not working

---

README.md
docs/source/introduction.rst

Update the badge in the README for currently supported Python versions.
Also update the required Python version in the [docs introduction](https://rich.readthedocs.io/en/latest/introduction.html#requirements).

docs: update supported python versions

---

rich/progress.py

Fixes https://github.com/Textualize/rich/issues/3706

docs and typing

---

CONTRIBUTORS.md
tests/test_logging.py

The commit 26345530ad6164bd57ed9c0861cef221a5e52f27 removes the `make_log` definition in `test_logging.py`, despite its usage still remaining when running the test module. As a result, my code editor flags it as an error. This PR removes the `make_log` usage.

Remove make log

---

rich/live.py

Fixes https://github.com/Textualize/rich/issues/3644

Self typing
